export const sliderData = [
    {
      title: 'Monday',
      Text:'Lab 3', 
    },
    {
      title: 'tuesday',
      Text:'Lab 3',
    },
    {
      title: 'Wednesday',
      Text:'Lab 3',
    },
  ];

  export const quote=[
    "The man who does not read books has no advantage over the one who cannot read them.” — Mark Twain", 
    "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.” — Malcolm X",
    "Teachers can open the door, but you must enter it yourself",
    "The beautiful thing about learning is that no one can take it away from you",
    "Education is the most powerful weapon you can use to change the world.", 
    "The mind is not a vessel to be filled but a fire to be ignited. ",
    "Don’t let what you cannot do interfere with what you can do",
    "A person who never made a mistake never tried anything new",
    "Learning is never done without errors and defeat", 
    "Never let the fear of striking out stop you from playing the game.",
    "Procrastination makes easy things hard and hard things harder.” ",
    "You don’t have to be great to start, but you have to start to be great",
    "The expert in anything was once a beginner", 
    "The way to get started is to quit talking and begin doing",
    "There are no shortcuts to any place worth going",
    "I think it’s possible to ordinary people to choose to be extraordinary",
    "I find that the harder I work, the more luck I seem to have", 
    "Genius is 10% inspiration, 90% perspiration ",
    "Motivation is what gets you started. Habit is what keeps you going",
    "Success is the sum of small efforts, repeated",
    "The best way to predict your future is to create it", 
    "The future belongs to those who believe in the beauty of their dreams ",
    "You are braver than you believe, stronger than you seem and smarter than you think",
    "Learn from yesterday. Live for today. Hope for tomorrow",
    "The more that you read, the more things you will know, the more that you learn, the more places you’ll go", 
    "Today a reader. Tomorrow a leader",
    "In a world where you can be anything, be kind.",
    "None of us is as smart as all of us.” ",
    "He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever", 
    "You have to be odd to be no.1. ",
    "You don’t have to be great to start, but you have to start to be great.",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway",
    "A learning curve is essential to growth", 
    "The most successful people in life are the ones who ask questions. They’re always learning. They’re always growing. They’re always pushing",
    "Be kind to yourself. Be kind to others. Be kind to the object you use in the classroom",
    "Treat others the way you would like to be treated",
    "Rules of the classroom: Be kind to others. Be ready to learn. Believe in yourself.", 
    "Logic will get you from A to B. Imagination will take you everywhere. ",
    "To raise new questions, new possibilities, to regard old problems from a new angle, requires creative imagination and marks real advance in science.",
    "To solve math problems, you need to know the basic mathematics before you can start applying it.",
    "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine", 
    "Time flies like an arrow; fruit flies like a banana ",
    "It is the time you have wasted for your rose that makes your rose so important",
    "Books have a unique way of stopping time in a particular moment and saying: Let’s not forget this",
    "Don't waste your time with explanations: people only hear what they want to hear.",
    "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.",
    "Don't spend time beating on a wall, hoping to transform it into a door.",
    "Time is the longest distance between two places",
    "They say time heals all wounds, but that presumes the source of the grief is finite",
    "This is a new year. A new beginning. And things will change.",
    "Scars have the strange power to remind us that our past is real.",
    "Here we are, trapped in the amber of the moment. There is no why.",
    "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.”",
    "Time is an illusion",
    "You may delay, but time will not",
    "Time is a game played beautifully by children",
    "There's never enough time to do all the nothing you want.",
    "Being with you and not being with you is the only way I have to measure time",
    "The strongest of all warriors are these two ",
    "Time takes it all, whether you want it to or not",
    "The future is uncertain but the end is always near",
    "A man must dream a long time in order to act with grandeur, and dreaming is nursed in darkness.",
    "Muddy water is best cleared by leaving it alone.",
    "As if you could kill time without injuring eternity.”",
    "Three o'clock is always too late or too early for anything you want to do.",
    "I'm not much but I'm all I have.",
    "Time is what keeps everything from happening at once.",
    "There is more to life than simply increasing its speed.",
    "Lost Time is never found again.",
    "There will be time, there will be time to prepare a face to meet the faces that you meet",
    "Time spent with a cat is never wasted",
    "Never waste a minute thinking about people you don't like",
    "The future starts today, not tomorrow.”",
    "Enjoy life. There's plenty of time to be dead.”",
    "Punctuality is the thief of time",
    "You will never find time for anything. If you want time, you must make it.”",
    "The past is a ghost, the future a dream and all we ever have is now.”",
    "Time's the thief of memory",
    "There's no advantage to hurrying through life",
    "Five minutes are enough to dream a whole life, that is how relative time is.”",
    "Time is precious, but truth is more precious than time",
    "The best things are never arrived at in haste. God is in no hurry; His plans are never rushed",
    "Eternity is in love with the productions of time.”",
    "Time moves slowly, but passes quickly",
    "When you are measuring life, you are not living it",
    "Realize deeply that the present moment is all you will ever have.",
    "Time has no meaning, Love will endure",
    "Time heals all wounds. But not this one. Not yet",
    "Real museums are places where Time is transformed into Space",
    "Time is the most valuable thing that a man can spend.”",
    "A revolution is not a bed of roses. A revolution is a struggle between the future and the past.”",
    "Nothing endures but change",
    "Time, as far as my father was concerned, was a gift you gave to other people",
    "Better three hours too soon than a minute too late",
    "Do not whine... Do not complain. Work harder. Spend more time alone",
    "You can find something truly important in an ordinary minute",
    "We are all migrants through time",
    "Time is Galleons, little brother",
    "I wasted time, and now doth time waste me",
    "Any time not spent on love is wasted.",
    "You forget, time doesn't exist anymore. You gave it to me",
   



  ];